#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

brew doctor

brew install ack
brew install coreutils
brew install grc
brew install git
brew install imagemagick
brew install autojump
brew install todo-ext
brew install tree
brew install hub