cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'wget'
brew 'youtube-dl'

cask 'iterm2'
cask '1password'
cask 'adium'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'transmission'
cask 'vlc'
cask 'skype'
cask 'caffeine'
cask 'dash'
cask 'evernote'
cask 'dropbox'
cask 'spotify'
cask 'transmit'
cask 'virtualbox'
cask 'colloquy'
cask 'macvim '
